config/routes.rb
Rails.application.routes.draw do

  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
  #ゲストログイン
  post '/guest_sign_in' => 'user/posts#guest'

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    resources :posts,only: [:show]
    resources :comments,only: [:index, :show, :edit, :update, :destroy]

    resources :users,only: [:index, :show, :edit, :update] do
      # adminから投稿削除した時にuser_idを辿ってredirectするためネストする
      resources :posts,only: [:destroy]
    end

    resources :tags,only: [:new,:create, :update, :destroy]
    get 'search' => 'users#search'
  end

  scope module: :user do
    root to:"homes#top"
    get'about' => 'homes#about', as:'about'
    resources :tags,only: [:new, :create, :destroy]
    resources :favorites,only: [:create, :destroy]
    resources :rankings,only: [:index]
    get 'users/my_page' => 'users#my_page'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/my_page/edit' => 'users#update'
    get 'users/withdraw' => 'users#withdraw'
    patch 'users/unsubscribe' => 'users#unsubscribe'

    resources :users do
     # memberでuser_idが含まれるルーティングになる
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts,only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    # どの投稿に紐づいたコメントなのかURLが判別できるようにする
      resources :comments, only: [:create, :destroy]
    end

    # 検索フォーム作成
    get 'search' => 'posts#search'
    get 'search_tag' => 'posts#search_tag'
  end

  # devise_for :admins
  # devise_for :users
      #   t.string :name
      # t.text :introduction
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

  # namespace :admin do
    # get 'posts/edit'
    # get 'posts/update'
  # end
  # namespace :admin do
  #   get 'comments/show'
  #   get 'comments/edit'
  #   get 'comments/update'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  #   get 'users/update'
  # end
  # namespace :user do
  #   get 'tags/new'
  #   get 'tags/create'
  #   get 'tags/destroy'
  # end
  # namespace :user do
  #   get 'relationships/index'
  #   get 'relationships/create'
  #   get 'relationships/destroy'
  # end
  # namespace :user do
  #   get 'favourites/index'
  #   get 'favourites/destroy'
  # end
  # namespace :user do
  #   get 'ranking/index'
  # end
  # namespace :user do
  #   get 'users/show'
  #   get 'users/edit'
  #   get 'users/update'
  #   get 'users/withdraw'
  #   get 'users/unsubscribe'
  # end
  # namespace :user do
  #   get 'comments/index'
  #   get 'comments/create'
  #   get 'comments/destroy'
  # end
  # namespace :user do
  #   get 'homes/top'
  #   get 'homes/about'
  # end
  # namespace :user do
  #   get 'rankings/index'
  # end
  # namespace :user do
  #   get 'posts/new'
  #   get 'posts/index'
  #   get 'posts/create'
  #   get 'posts/show'
  #   get 'posts/update'
  #   get 'posts/destroy'
  # end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def search
    @users = User.search(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end

  def show
    @user = User.find(params[:id])
    #ユーザーが投稿したものを表示
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to admin_user_path(@user.id), notice: 'You have updated book successfully'
    else
     @user = User.find(params[:id])
     render :edit
    end
  end

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :introduction, :email, :is_deleted)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  # ログインユーザーのみコメント機能使用可
  before_action :authenticate_user!

  def create
    # コメントをする対象の投稿(travel_record)のインスタンスを作成
    @post =Post.find(params[:post_id])
    #投稿に紐づいたコメントを作成
    @comment = @post.comments.build(comment_params)
    @comments_latest3 = @post.comments.limit(3).offset(params[:offset])
    # コメント投稿者(user)のidを代入
    @comment.user_id = current_user.id
    @comments = @post.comments.order(created_at: :desc)
    @comments_next = @post.comments.order(created_at: :desc).offset(3)
    if @comment.save
      flash.now[:notice] = "コメントの投稿に成功しました。"
    else
      flash.now[:alert] ="コメントの投稿に失敗しました。"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
      @post = Post.find(params[:post_id])
      @comments = @post.comments.order(created_at: :desc)
      @comments_next = @comments.offset(3)

    #@comment.post_idから親のpost情報を取得し@comments = @post.comments
    flash.now[:notice] = "コメントを削除しました。"
    else
    redirect_to posts_path
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :post_id)
    end

    def set_comments
      # postに紐づくcommtnsを新着順で取得
      @post_comments = @post.comments.includes(:user).order('created_at DESC')
    end

end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController

  # ログインユーザーのみお気に入り機能使用可
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @favorite = current_user.favorites.new(post_id: @post.id)
    @favorite.save
  end

  def destroy
    @post = Favorite.find_by(params[:id]).post
    if favorite = Favorite.find_by(params[:id])
      favorite.destroy
    end
  end
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController

  # newとeditはログインユーザーのみ遷移できる
  before_action :authenticate_user!,only: [:new, :edit]
  before_action :correct_post,only: [:edit, :update]

  def new
    # current_userからbuildで書くとuser_id作られる
    @post = current_user.posts.build
    # postする時にtagが作られるようにする
    @post_tag = @post.post_tags.build
    @post_tag.build_tag
    @posts = Post.page(params[:page]).per(10)
    @tag_list = Tag.all
  end

  def index
    @posts = Post.all
  end
  def search
    @posts = Post.search(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end

  def search_tag
    @posts = Post.search_tag(params[:keyword])
    @keyword = params[:keyword]
    render 'index'
  end


  def create
    ActiveRecord::Base.transaction do
      @post = current_user.posts.build(post_params)
      # タグを,で区切って複数保存
      tag_names = tag_params.dig(:tags, :names).split(/[[:blank:]]+/)
      if @post.save
        @post.save_tag(tag_names)
        redirect_to post_path(@post)
      else
        render :new
      end
    end
  end

  def show
    # 投稿に対して、いいねを紐付ける
    @post = Post.includes(:favorites).find(params[:id])

    #投稿した人の名前表示
    @user = @post.user
    # コメント一覧表示で使用する全コメントデータを代入（新着順で表示）
    @comments = @post.comments.order(created_at: :desc).first(3)
    @comments_next = @post.comments.order(created_at: :desc).offset(3)
    # コメントの作成
    @comment = Comment.new
    # 緯度経度を保存する
    gon.lng = @post.longitude
    gon.lat = @post.latitude
  end

  def edit
    @post = Post.find(params[:id])
    gon.lng = @post.longitude
    gon.lat = @post.latitude
  end

  def update
    ActiveRecord::Base.transaction do
      @post = Post.find(params[:id])
      # 入力されたタグを受け取る
      tag_names = tag_params.dig(:tags, :names).split(/[[:blank:]]+/)
      if @post.user_id == current_user.id
        @post.update(post_params)
        @post.save_tag(tag_names)
        redirect_to post_path(@post.id), notice: '更新完了しました:)'
      else
        render :edit
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      @post.destroy
      redirect_to users_my_page_path
    else
       redirect_to posts_path
    end
  end

  #ゲストログイン用
  def guest
    user          = User.new(user_params)
    user.name     = "ゲストユーザー"+SecureRandom.alphanumeric(10)
    user.email    = SecureRandom.alphanumeric(10) + "@email.com"
    user.password = SecureRandom.alphanumeric(10)
    user.save!
    sign_in user
    redirect_to posts_path
  end

  # ログインユーザー以外がeditに遷移しようとした場合投稿一覧に遷移する
  def correct_post
      @post = Post.find(params[:id])
    unless @post.user.id == current_user.id
      redirect_to posts_path
    end
  end

  private

  def user_params
    params.permit(
      :name,
      :email,
      :password)
  end

  def post_params
    params.require(:post).permit(
      :title,
      :place,
      :tag_list,
      :image,
      :introduction,
      :latitude,
      :longitude
      )
  end

  def tag_params
    params.require(:post).permit(
      tags: [:names])
  end

  def currect_user
    @post = Post.find(params[:id])
    @user = @post.user
    redirect_to posts_path unless @user == current_user
  end

end

app/controllers/user/rankings_controller.rb
class User::RankingsController < ApplicationController

  def index
    # お気に入り数ランキング
    @favorite_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
    # 投稿のコメント数ランキング
    @comment_ranks = Post.find(Comment.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))
  end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/relationships_controller.rb
class User::RelationshipsController < ApplicationController

  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
  # フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  # フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end


end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController

  before_action :user_state, only: [:create]

   protected
  # 退会しているかを判断するメソッド
  def user_state
    ##入力されたemailからアカウントを1件取得
    @user = User.find_by(email: params[:user][:email])
    ## アカウントを取得できなかった場合、このメソッドを終了する
    return if !@user
    ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted
      ## 【処理内容3】
      # if @customer.is_deleted == ture
      redirect_to new_user_registration_path
      # end
    end
  end

end

app/controllers/user/tags_controller.rb
class User::TagsController < ApplicationController

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  # ログインユーザーがshowへ遷移する時はマイページに遷移する
  before_action :redirect_my_page, only: [:show]
  before_action :authenticate_user!

  def my_page
    @user = current_user
    @posts = @user.posts
  end

  def favorites
    @user = User.find(params[:id])
    # user_idがユーザーのお気に入りのレコードを取得
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
     redirect_to users_my_page_path(current_user), notice: 'You have updated book successfully'
    else
     render :edit
    end
  end

  def unsubscribe
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  #ストロングパラメーター
  def user_params
    params.require(:user).permit(:name, :introduction, :email, :profile_image)
  end

  # ログインユーザーなら、マイページに遷移する
  def redirect_my_page
    @user = User.find(params[:id])
    redirect_to users_my_page_path if @user == current_user
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/helpers/user/favourites_helper.rb
module User::FavouritesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/user/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-4 col-md-4">
      <div class="text-center mt-4"><h3>会員情報編集</h3></div>
    </div>
  </div> fa-2x

  <div class="row">
    <div class="offset-md-2 col-md-4 mt-2 mb-3">

      <%= form_with model: @user, url: users_my_page_edit_path(@user.id), method: :patch do |f| %>

      <div class="field mt-4">
        <%= f.label :プロフィール写真 %>
        <%= f.file_field :profile_image, accept: "image/*", class:'form-control-file', id: 'profile_image' %>
      </div>

        <!--画像表示の追記-->
      <div id="user_profile_image", class="mt-2"></div>
      <div id="new-image", class="mt-2"></div>

    </div>

    <div class = "col-md-5 mt-2">
      <%#= form_with model: @user, url: users_my_page_edit_path(@user.id), method: :patch do |f| %>
      <table class="table table-borderless">
        <thead></thead>
        <tbody>

          <tr>
            <th></th>
            <th class="text-right"><%= link_to "退会", users_withdraw_path, class:'btn btn-outline-danger' %></th>
          </tr>

          <tr>
            <th><%= f.label :name, "アカウント名" %></th>
            <th><%= f.text_field :name, autofocus: true, id:"name", class:'form-control' %></th>
          </tr>

          <tr>
            <th><%= f.label :name, "自己紹介" %></th>
            <th><%= f.text_area :introduction, autofocus: true, id:"introduction", class:'form-control' %></th>
          </tr>

          <tr>
            <th><%= f.label :email, "メールアドレス" %></th>
            <th><%= f.text_field :email, id:"email", class:'form-control' %></th>
          </tr>

        </tbody>
      </table>
    </div>
  </div>

  <div class="row mt-4">

    <div class = "offset-md-4 col-md-4 p-1 mb-5">
      <%= f.submit "更新", class:'btn btn-outline-dark btn-block' %>
    </div>
      <% end %>

  </div>
</div>
<!--<h1>User::Users#edit</h1>-->
<!--<p>Find me in app/views/user/users/edit.html.erb</p>-->

app/views/user/users/favorites.html.erb
<div class="container">
  <div class = "row">
    <div class="col-md-6" >

      <h3 class=" mb-4 mt-1">
        お気に入り一覧
        <%= link_to "戻る", request.referer, class: "btn btn-outline-secondary mx-3 mb-1" %>
      </h3>

    </div>
  </div>

  <div class = "row">
    <% @favorite_posts.each do |post| %>

    <div class = "col-md-2 mt-3 ml-1">
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.get_image(500,500), class: 'user-favorites-image' %></br>
        <%= post.title %></br>
      <% end %>
    </div>
    <% end %>

  </div>
</div>

app/views/user/users/my_page.html.erb
<div class="container my-5">
  <div class = "row">
    <div class = "offset-md-2 col-md-3">
      <!--アカウント登録情報-->
      <div class="text-center"><strong><h2 class="mb-4"><%= @user.name %></h2></strong></div>
      <div class="text-center mt-1"><%= image_tag @user.get_profile_image(230,230) %></div>
      <div class="text-center mt-1"><h5><%= @user.introduction %></h5></div>
      <div class="text-center mt-1"><h5><%= @user.email %></h5></div>
      <!--ログインユーザーのみ編集を表示-->
      <% if user_signed_in? %>
        <%= link_to users_my_page_edit_path(@user.id),  class: 'btn btn-outline-dark btn-block' do %>
          編集する
        <% end %>
      <% end %>

      <%= link_to "お気に入り写真", favorites_user_path(@user), class: 'btn btn-outline-dark btn-block text-center' %>
      <%= link_to "フォローリスト", user_followings_path(@user), class: 'btn btn-outline-dark btn-block' %>
      <%= link_to "フォロワー", user_followers_path(@user), class: 'btn btn-outline-dark btn-block' %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn btn-outline-dark btn-block mb-3' %>
    </div>
    <!--ログインユーザーの投稿写真-->
    <div class="text-center offset-md-1 col-md-4  mt-2">
        <!--投稿写真並べて表示-->
        <% @posts.each do |post| %>
          <%= link_to post_path(post.id) do %>
            <%= image_tag post.get_image(500,500), class: 'user-my_page-image' %></br>
            <%= post.title %></br>
          <% end %>
        <% end %>
    </div>
  </div>
</div>

app/views/user/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-5 offset-md-1 text-center"><h1><%= @user.name %></h1></div>
  </div>

  <div class="row">
    <div class="offset-md-1 col-md-5 text-center">
      <!--アカウント登録情報-->
      <%= image_tag @user.get_profile_image(230,230) %>
      <div><h5><%= @user.introduction %></h5></div>
    </div>

    <div class = "col-md-4 offset-md-1 text-center">
      <%= link_to "お気に入り写真", favorites_user_path(@user), class: 'btn btn-outline-dark btn-block mt-4' %>
       <!--フォローボタン-->
      <% if current_user.following?(@user) %>
        <%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete, class: 'btn btn-info btn-block mt-4 mb-3' %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: 'btn btn-outline-dark btn-block mt-4 mb-4' %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @posts.each do |post| %>
    <!--ユーザーの投稿写真-->
    <div class="col-md-2 mt-3 mr-2 ml-2">
        <!--投稿写真並べて表示-->
      <%= link_to post_path(post.id) do %>
        <%= image_tag post.get_image(500,500), class: 'admin-show-image' %></br>
        <%= post.title %></br>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/user/users/withdraw.html.erb
<div class="container　mt-5">
  <div class="row">
    <div class="offset-md-2 col-md-8 my-5">

      <strong><h2 class="text-center mt-5">本当に退会しますか？</h2></strong></br>
      <h6 class="text-center">退会すると、登録情報や</h6></br>
      <h6 class="text-center">これまで投稿したものは閲覧できなくなります</h6></br>

      <div class="row mt-3">

        <div class="col-md-4 mx-auto my-3">
          <%= link_to "絶景の共有を続ける", users_my_page_path, class:'btn btn-primary btn-block' %>
        </div>

        <div class="col-md-4 mx-auto my-3">
           <%= link_to "退会する", users_unsubscribe_path, method: :patch, class:'btn btn-danger btn-block' %>
        </div>
      </div>

    </div>
  </div>
</div>


<!--<h1>User::Users#withdraw</h1>-->
<!--<p>Find me in app/views/user/users/withdraw.html.erb</p>-->