config/routes.rb
Rails.application.routes.draw do

  devise_for :user, skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}
  #ゲストログイン
  post '/guest_sign_in' => 'user/posts#guest'

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "homes#top"
    resources :posts,only: [:show]
    resources :comments,only: [:index, :show, :edit, :update, :destroy]

    resources :users,only: [:index, :show, :edit, :update] do
      # adminから投稿削除した時にuser_idを辿ってredirectするためネストする
      resources :posts,only: [:destroy]
    end

    resources :tags,only: [:new,:create, :update, :destroy]
    get 'search' => 'users#search'
  end

  scope module: :user do
    root to:"homes#top"
    get'about' => 'homes#about', as:'about'
    resources :tags,only: [:new, :create, :destroy]
    resources :favorites,only: [:create, :destroy]
    resources :rankings,only: [:index]
    get 'users/my_page' => 'users#my_page'
    get 'users/my_page/edit' => 'users#edit'
    patch 'users/my_page/edit' => 'users#update'
    get 'users/withdraw' => 'users#withdraw'
    patch 'users/unsubscribe' => 'users#unsubscribe'

    resources :users do
     # memberでuser_idが含まれるルーティングになる
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end

    resources :posts,only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    # どの投稿に紐づいたコメントなのかURLが判別できるようにする
      resources :comments, only: [:create, :destroy]
    end

    # 検索フォーム作成
    get 'search' => 'posts#search'
    get 'search_tag' => 'posts#search_tag'
  end

  # devise_for :admins
  # devise_for :users
      #   t.string :name
      # t.text :introduction
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

  # namespace :admin do
    # get 'posts/edit'
    # get 'posts/update'
  # end
  # namespace :admin do
  #   get 'comments/show'
  #   get 'comments/edit'
  #   get 'comments/update'
  # end
  # namespace :admin do
  #   get 'users/index'
  #   get 'users/show'
  #   get 'users/edit'
  #   get 'users/update'
  # end
  # namespace :user do
  #   get 'tags/new'
  #   get 'tags/create'
  #   get 'tags/destroy'
  # end
  # namespace :user do
  #   get 'relationships/index'
  #   get 'relationships/create'
  #   get 'relationships/destroy'
  # end
  # namespace :user do
  #   get 'favourites/index'
  #   get 'favourites/destroy'
  # end
  # namespace :user do
  #   get 'ranking/index'
  # end
  # namespace :user do
  #   get 'users/show'
  #   get 'users/edit'
  #   get 'users/update'
  #   get 'users/withdraw'
  #   get 'users/unsubscribe'
  # end
  # namespace :user do
  #   get 'comments/index'
  #   get 'comments/create'
  #   get 'comments/destroy'
  # end
  # namespace :user do
  #   get 'homes/top'
  #   get 'homes/about'
  # end
  # namespace :user do
  #   get 'rankings/index'
  # end
  # namespace :user do
  #   get 'posts/new'
  #   get 'posts/index'
  #   get 'posts/create'
  #   get 'posts/show'
  #   get 'posts/update'
  #   get 'posts/destroy'
  # end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColourPen</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="background">
    <header>
      <nav class= "navbar navbar-expand-lg navbar-light site-header pb-3 pt-3">
        <div class="container">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <i class="fas fa-pen fa-2x fa-rotate-90"></i>
            <h1 class="navbar-brand title">ColourPen</h1>
          <% end %>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown" >
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li><%= link_to "投稿", new_post_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "絶景一覧", posts_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "ランキング", rankings_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "マイページ", users_my_page_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to "会員一覧", admin_users_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mx-1 my-1" %></li>
              <% else %>
                <li><%= link_to "会員登録", new_user_registration_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "ログイン", new_user_session_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "ゲスト", guest_sign_in_path,  method: :post, class: "btn btn-outline-secondary mx-1 my-1" %></li>
                <li><%= link_to "絶景一覧", posts_path, class: "btn btn-outline-secondary mx-1 my-1" %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
    <div id="scroll-to-top" class="d-flex align-items-center justify-content-center">
      <i class="fas fa-share fa-rotate-270 mt-5 mb-5 scroll"></i>
    </div>
  </body>

</html>